spring.application.name=clubpadel

# Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-dry-bread-b1nzmpy7-pooler.c-5.eu-central-1.aws.neon.tech/cpm?sslmode=require&channel_binding=require
spring.datasource.username=cpm_owner
spring.datasource.password=npg_0AGZwoRfsDY9
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Servidor
server.port=8080

# JWT
jwt.secret=ClaveSecretaSuperLargaParaFirmarTokensJWT2026PadelClub
jwt.expiration=86400000
